### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by havvvsen** [ImRayy/nixos-dots#2]
I dont understand the commits removed ags...are you using ags as your status bar or its waybar but pops up ags widgets ?

How do I get your ags dots only

**Comment by ImRayy** [comment]
> I dont understand the commits removed ags...are you using ags as your status bar or its waybar but pops up ags widgets ?
> 

I am using AGS bar, Since I make frequent changes to my dots, it was hard to manage both home-manager and AGS dotfiles together, so I created a dedicated repo for AGS dots. 

> How do I get your ags dots only

here you go: https://github.com/ImRayy/ags-dots.

**Comment by havvvsen** [comment]
> > I dont understand the commits removed ags...are you using ags as your status bar or its waybar but pops up ags widgets ?
> 
> I am using AGS bar, Since I make frequent changes to my dots, it was hard to manage both home-manager and AGS dotfiles together, so I created a dedicated repo for AGS dots.
> 
> > How do I get your ags dots only
> 
> here you go: https://github.com/ImRayy/ags-dots.

I see .Thanks_
